name: Build and deploy to permaweb

on:
  #allows manual triggering from Actions tab
  workflow_dispatch:
  # push:
  #   branches: [main]

jobs:
  publish:
    name: Publish to permaweb
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "20.x"
      - run: npm ci
      - run: npm run build
      - run: npm run deploy
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
